config/routes.rb
Rails.application.routes.draw do

  resources :mdl_resources
  resources :mdl_contexts
  resources :mdl_role_assignments
  root 'welcome#index'

  resources :mdl_events
  resources :mdl_forum_posts
  resources :mdl_forum_discussions
  resources :mdl_forums
  resources :mdl_courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mdl_users

 get 'mdl_events/eventosPorCurso/:courseid', to: 'mdl_events#eventosPorCurso'
get 'mdl_users/', to: 'mdl_users#index'
  get 'mdl_forums/forosPorCurso/:course', to: 'mdl_forums#forosPorCurso'
  get 'mdl_forum_discussions/discusionesPorForo/:forum', to: 'mdl_forum_discussions#discusionesPorForo'
  get 'mdl_forums_posts/postPorDiscusionPrincipal/:discussion', to: 'mdl_forum_posts#postPorDiscusionPrincipal'
  get 'mdl_forums_posts/postRespuestas/:discussion/', to: 'mdl_forum_posts#postRespuestas'
  get 'mdl_resources/obtenerRecursosPorCurso/:course', to: 'mdl_resources#obtenerRecursosPorCurso'
  post 'mdl_contexts/misCursos/', to: 'mdl_contexts#misCursos'
  post 'mdl_users/verifEmail', to: 'mdl_users#verifEmail'
  get 'mdl_users/emailErroneo', to: 'mdl_users#emailErroneo'
  get 'mdl_users/vcontrasena/:contrasena', to: 'mdl_users#vcontrasena'
  get 'mdl_contexts/course/:id', to: 'mdl_contexts#course'
  get 'mdl_context/buscar', to: 'mdl_context#buscar'
  get 'mdl_resources/sinRecursos/:course', to: 'mdl_resources#sinRecursos'
  get 'mdl_events/sinEventos/:courseid', to: 'mdl_events#sinEventos'
  get 'mdl_forums/sinForos', to: 'mdl_forums#sinForos'
  get 'mdl_forum_discussions/sinDiscusiones', to: 'mdl_forum_discussions#sinDiscusiones'
  get 'mdl_forum_posts/sinPosts',to: 'mdl_forum_posts#sinPosts'
end

app/models/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: 'from@example.com'
  layout 'mailer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mdl_context.rb
class MdlContext < ApplicationRecord
    self.table_name = "mdl_context"
     has_many :mdl_role_assignments
     has_many :mdl_courses 
end

app/models/mdl_course.rb
class MdlCourse < ApplicationRecord

    self.table_name = "mdl_course"
    belongs_to :mdl_context
end

app/models/mdl_event.rb
class MdlEvent < ApplicationRecord

self.table_name = "mdl_event"

end

app/models/mdl_forum.rb
class MdlForum < ApplicationRecord

self.table_name = "mdl_forum"
self.inheritance_column = :_type_disabled
end

app/models/mdl_forum_discussion.rb
class MdlForumDiscussion < ApplicationRecord

  self.table_name = "mdl_forum_discussions"

end

app/models/mdl_forum_post.rb
class MdlForumPost < ApplicationRecord

  self.table_name = "mdl_forum_posts"

end

app/models/mdl_resource.rb
class MdlResource < ApplicationRecord

    self.table_name = "mdl_resource"


end

app/models/mdl_role_assignment.rb
class MdlRoleAssignment < ApplicationRecord

   belongs_to :mdl_context
   


end

app/models/mdl_user.rb
class MdlUser< ApplicationRecord

  has_secure_password

  self.table_name = "mdl_user"


end

app/controllers/mdl_role_assignments_controller.rb
class MdlRoleAssignmentsController < ApplicationController
  before_action :set_mdl_role_assignment, only: [:show, :edit, :update, :destroy]

  # GET /mdl_role_assignments
  # GET /mdl_role_assignments.json
  def index
    @mdl_role_assignments = MdlRoleAssignment.all
  end

  # GET /mdl_role_assignments/1
  # GET /mdl_role_assignments/1.json
  def show
  end

  # GET /mdl_role_assignments/new
  def new
    @mdl_role_assignment = MdlRoleAssignment.new
  end

  # GET /mdl_role_assignments/1/edit
  def edit
  end

  # POST /mdl_role_assignments
  # POST /mdl_role_assignments.json
  def create
    @mdl_role_assignment = MdlRoleAssignment.new(mdl_role_assignment_params)

    respond_to do |format|
      if @mdl_role_assignment.save
        format.html { redirect_to @mdl_role_assignment, notice: 'Mdl role assignment was successfully created.' }
        format.json { render :show, status: :created, location: @mdl_role_assignment }
      else
        format.html { render :new }
        format.json { render json: @mdl_role_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mdl_role_assignments/1
  # PATCH/PUT /mdl_role_assignments/1.json
  def update
    respond_to do |format|
      if @mdl_role_assignment.update(mdl_role_assignment_params)
        format.html { redirect_to @mdl_role_assignment, notice: 'Mdl role assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @mdl_role_assignment }
      else
        format.html { render :edit }
        format.json { render json: @mdl_role_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mdl_role_assignments/1
  # DELETE /mdl_role_assignments/1.json
  def destroy
    @mdl_role_assignment.destroy
    respond_to do |format|
      format.html { redirect_to mdl_role_assignments_url, notice: 'Mdl role assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mdl_role_assignment
      @mdl_role_assignment = MdlRoleAssignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mdl_role_assignment_params
      params.require(:mdl_role_assignment).permit(:roleid, :contextid, :userid, :timemodified, :modifierid, :component, :itemid, :sortorder)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mdl_contexts_helper.rb
module MdlContextsHelper
end

app/helpers/mdl_courses_helper.rb
module MdlCoursesHelper
end

app/helpers/mdl_events_helper.rb
module MdlEventsHelper
end

app/helpers/mdl_forums_helper.rb
module MdlForumsHelper
end

app/helpers/mdl_resources_helper.rb
module MdlResourcesHelper
end

app/helpers/mdl_role_assignments_helper.rb
module MdlRoleAssignmentsHelper
end

app/helpers/mdl_users_helper.rb
module MdlUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mdl_role_assignments/_form.html.erb
<%= form_for(mdl_role_assignment) do |f| %>
  <% if mdl_role_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mdl_role_assignment.errors.count, "error") %> prohibited this mdl_role_assignment from being saved:</h2>

      <ul>
      <% mdl_role_assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roleid %>
    <%= f.text_field :roleid %>
  </div>

  <div class="field">
    <%= f.label :contextid %>
    <%= f.text_field :contextid %>
  </div>

  <div class="field">
    <%= f.label :userid %>
    <%= f.text_field :userid %>
  </div>

  <div class="field">
    <%= f.label :timemodified %>
    <%= f.text_field :timemodified %>
  </div>

  <div class="field">
    <%= f.label :modifierid %>
    <%= f.text_field :modifierid %>
  </div>

  <div class="field">
    <%= f.label :component %>
    <%= f.text_field :component %>
  </div>

  <div class="field">
    <%= f.label :itemid %>
    <%= f.text_field :itemid %>
  </div>

  <div class="field">
    <%= f.label :sortorder %>
    <%= f.text_field :sortorder %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mdl_role_assignments/edit.html.erb
<h1>Editing Mdl Role Assignment</h1>

<%= render 'form', mdl_role_assignment: @mdl_role_assignment %>

<%= link_to 'Show', @mdl_role_assignment %> |
<%= link_to 'Back', mdl_role_assignments_path %>

app/views/mdl_role_assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mdl Role Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Roleid</th>
      <th>Contextid</th>
      <th>Userid</th>
      <th>Timemodified</th>
      <th>Modifierid</th>
      <th>Component</th>
      <th>Itemid</th>
      <th>Sortorder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mdl_role_assignments.each do |mdl_role_assignment| %>
      <tr>
        <td><%= mdl_role_assignment.roleid %></td>
        <td><%= mdl_role_assignment.contextid %></td>
        <td><%= mdl_role_assignment.userid %></td>
        <td><%= mdl_role_assignment.timemodified %></td>
        <td><%= mdl_role_assignment.modifierid %></td>
        <td><%= mdl_role_assignment.component %></td>
        <td><%= mdl_role_assignment.itemid %></td>
        <td><%= mdl_role_assignment.sortorder %></td>
        <td><%= link_to 'Show', mdl_role_assignment %></td>
        <td><%= link_to 'Edit', edit_mdl_role_assignment_path(mdl_role_assignment) %></td>
        <td><%= link_to 'Destroy', mdl_role_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mdl Role Assignment', new_mdl_role_assignment_path %>

app/views/mdl_role_assignments/new.html.erb
<h1>New Mdl Role Assignment</h1>

<%= render 'form', mdl_role_assignment: @mdl_role_assignment %>

<%= link_to 'Back', mdl_role_assignments_path %>

app/views/mdl_role_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roleid:</strong>
  <%= @mdl_role_assignment.roleid %>
</p>

<p>
  <strong>Contextid:</strong>
  <%= @mdl_role_assignment.contextid %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @mdl_role_assignment.userid %>
</p>

<p>
  <strong>Timemodified:</strong>
  <%= @mdl_role_assignment.timemodified %>
</p>

<p>
  <strong>Modifierid:</strong>
  <%= @mdl_role_assignment.modifierid %>
</p>

<p>
  <strong>Component:</strong>
  <%= @mdl_role_assignment.component %>
</p>

<p>
  <strong>Itemid:</strong>
  <%= @mdl_role_assignment.itemid %>
</p>

<p>
  <strong>Sortorder:</strong>
  <%= @mdl_role_assignment.sortorder %>
</p>

<%= link_to 'Edit', edit_mdl_role_assignment_path(@mdl_role_assignment) %> |
<%= link_to 'Back', mdl_role_assignments_path %>