config/routes.rb
Rails.application.routes.draw do

  resources :mdl_resources
  resources :mdl_contexts
  resources :mdl_role_assignments
  root 'welcome#index'

  resources :mdl_events
  resources :mdl_forum_posts
  resources :mdl_forum_discussions
  resources :mdl_forums
  resources :mdl_courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mdl_users

 get 'mdl_events/eventosPorCurso/:courseid', to: 'mdl_events#eventosPorCurso'
get 'mdl_users/', to: 'mdl_users#index'
  get 'mdl_forums/forosPorCurso/:course', to: 'mdl_forums#forosPorCurso'
  get 'mdl_forum_discussions/discusionesPorForo/:forum', to: 'mdl_forum_discussions#discusionesPorForo'
  get 'mdl_forums_posts/postPorDiscusionPrincipal/:discussion', to: 'mdl_forum_posts#postPorDiscusionPrincipal'
  get 'mdl_forums_posts/postRespuestas/:discussion/', to: 'mdl_forum_posts#postRespuestas'
  get 'mdl_resources/obtenerRecursosPorCurso/:course', to: 'mdl_resources#obtenerRecursosPorCurso'
  post 'mdl_contexts/misCursos/', to: 'mdl_contexts#misCursos'
  post 'mdl_users/verifEmail', to: 'mdl_users#verifEmail'
  get 'mdl_users/emailErroneo', to: 'mdl_users#emailErroneo'
  get 'mdl_users/vcontrasena/:contrasena', to: 'mdl_users#vcontrasena'
  get 'mdl_contexts/course/:id', to: 'mdl_contexts#course'
  get 'mdl_context/buscar', to: 'mdl_context#buscar'
  get 'mdl_resources/sinRecursos/:course', to: 'mdl_resources#sinRecursos'
  get 'mdl_events/sinEventos/:courseid', to: 'mdl_events#sinEventos'
  get 'mdl_forums/sinForos', to: 'mdl_forums#sinForos'
  get 'mdl_forum_discussions/sinDiscusiones', to: 'mdl_forum_discussions#sinDiscusiones'
  get 'mdl_forum_posts/sinPosts',to: 'mdl_forum_posts#sinPosts'
end

app/models/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: 'from@example.com'
  layout 'mailer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mdl_context.rb
class MdlContext < ApplicationRecord
    self.table_name = "mdl_context"
     has_many :mdl_role_assignments
     has_many :mdl_courses 
end

app/models/mdl_course.rb
class MdlCourse < ApplicationRecord

    self.table_name = "mdl_course"
    belongs_to :mdl_context
end

app/models/mdl_event.rb
class MdlEvent < ApplicationRecord

self.table_name = "mdl_event"

end

app/models/mdl_forum.rb
class MdlForum < ApplicationRecord

self.table_name = "mdl_forum"
self.inheritance_column = :_type_disabled
end

app/models/mdl_forum_discussion.rb
class MdlForumDiscussion < ApplicationRecord

  self.table_name = "mdl_forum_discussions"

end

app/models/mdl_forum_post.rb
class MdlForumPost < ApplicationRecord

  self.table_name = "mdl_forum_posts"

end

app/models/mdl_resource.rb
class MdlResource < ApplicationRecord

    self.table_name = "mdl_resource"


end

app/models/mdl_role_assignment.rb
class MdlRoleAssignment < ApplicationRecord

   belongs_to :mdl_context
   


end

app/models/mdl_user.rb
class MdlUser< ApplicationRecord

  has_secure_password

  self.table_name = "mdl_user"


end

app/controllers/mdl_courses_controller.rb
class MdlCoursesController < ApplicationController
  before_action :set_mdl_course, only: [:show, :edit, :update, :destroy]

  # GET /mdl_courses
  # GET /mdl_courses.json
  def index
    @terminoABuscar = params[:terminoABuscar]
    @mdl_course = MdlCourse.where(:fullname => @terminoABuscar)
  end





  def create
    @mdl_course = MdlCourse.new(mdl_course_params)

    respond_to do |format|
      if @mdl_course.save
        format.html { redirect_to @mdl_course, notice: 'Mdl course was successfully created.' }
        format.json { render :show, status: :created, location: @mdl_course }
      else
        format.html { render :new }
        format.json { render json: @mdl_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mdl_courses/1
  # PATCH/PUT /mdl_courses/1.json
  def update
    respond_to do |format|
      if @mdl_course.update(mdl_course_params)
        format.html { redirect_to @mdl_course, notice: 'Mdl course was successfully updated.' }
        format.json { render :show, status: :ok, location: @mdl_course }
      else
        format.html { render :edit }
        format.json { render json: @mdl_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mdl_courses/1
  # DELETE /mdl_courses/1.json
  def destroy
    @mdl_course.destroy
    respond_to do |format|
      format.html { redirect_to mdl_courses_url, notice: 'Mdl course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mdl_course
      @mdl_course = MdlCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mdl_course_params
      params.require(:mdl_course).permit(:category, :sortorder, :fullname, :shortname, :idnumber, :summary, :summaryformat, :format, :showgrades, :newsitems, :startdate, :marker, :maxbytes, :legacyfiles, :showreports, :visible, :visibleold, :groupmode, :groupmodeforce, :defaultgroupingid, :lang, :calendartype, :theme, :timecreated, :timemodified, :requested, :enablecompletion, :completionnotify, :cacherev)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mdl_contexts_helper.rb
module MdlContextsHelper
end

app/helpers/mdl_courses_helper.rb
module MdlCoursesHelper
end

app/helpers/mdl_events_helper.rb
module MdlEventsHelper
end

app/helpers/mdl_forums_helper.rb
module MdlForumsHelper
end

app/helpers/mdl_resources_helper.rb
module MdlResourcesHelper
end

app/helpers/mdl_users_helper.rb
module MdlUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mdl_courses/_form.html.erb
<%= form_for(mdl_course) do |f| %>
  <% if mdl_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mdl_course.errors.count, "error") %> prohibited this mdl_course from being saved:</h2>

      <ul>
      <% mdl_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :sortorder %>
    <%= f.text_field :sortorder %>
  </div>

  <div class="field">
    <%= f.label :fullname %>
    <%= f.text_field :fullname %>
  </div>

  <div class="field">
    <%= f.label :shortname %>
    <%= f.text_field :shortname %>
  </div>

  <div class="field">
    <%= f.label :idnumber %>
    <%= f.text_field :idnumber %>
  </div>

  <div class="field">
    <%= f.label :summary %>
    <%= f.text_area :summary %>
  </div>

  <div class="field">
    <%= f.label :summaryformat %>
    <%= f.number_field :summaryformat %>
  </div>

  <div class="field">
    <%= f.label :format %>
    <%= f.text_field :format %>
  </div>

  <div class="field">
    <%= f.label :showgrades %>
    <%= f.number_field :showgrades %>
  </div>

  <div class="field">
    <%= f.label :newsitems %>
    <%= f.number_field :newsitems %>
  </div>

  <div class="field">
    <%= f.label :startdate %>
    <%= f.text_field :startdate %>
  </div>

  <div class="field">
    <%= f.label :marker %>
    <%= f.text_field :marker %>
  </div>

  <div class="field">
    <%= f.label :maxbytes %>
    <%= f.text_field :maxbytes %>
  </div>

  <div class="field">
    <%= f.label :legacyfiles %>
    <%= f.number_field :legacyfiles %>
  </div>

  <div class="field">
    <%= f.label :showreports %>
    <%= f.number_field :showreports %>
  </div>

  <div class="field">
    <%= f.label :visible %>
    <%= f.check_box :visible %>
  </div>

  <div class="field">
    <%= f.label :visibleold %>
    <%= f.check_box :visibleold %>
  </div>

  <div class="field">
    <%= f.label :groupmode %>
    <%= f.number_field :groupmode %>
  </div>

  <div class="field">
    <%= f.label :groupmodeforce %>
    <%= f.number_field :groupmodeforce %>
  </div>

  <div class="field">
    <%= f.label :defaultgroupingid %>
    <%= f.text_field :defaultgroupingid %>
  </div>

  <div class="field">
    <%= f.label :lang %>
    <%= f.text_field :lang %>
  </div>

  <div class="field">
    <%= f.label :calendartype %>
    <%= f.text_field :calendartype %>
  </div>

  <div class="field">
    <%= f.label :theme %>
    <%= f.text_field :theme %>
  </div>

  <div class="field">
    <%= f.label :timecreated %>
    <%= f.text_field :timecreated %>
  </div>

  <div class="field">
    <%= f.label :timemodified %>
    <%= f.text_field :timemodified %>
  </div>

  <div class="field">
    <%= f.label :requested %>
    <%= f.check_box :requested %>
  </div>

  <div class="field">
    <%= f.label :enablecompletion %>
    <%= f.check_box :enablecompletion %>
  </div>

  <div class="field">
    <%= f.label :completionnotify %>
    <%= f.check_box :completionnotify %>
  </div>

  <div class="field">
    <%= f.label :cacherev %>
    <%= f.text_field :cacherev %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mdl_courses/edit.html.erb
<h1>Editing Mdl Course</h1>

<%= render 'form', mdl_course: @mdl_course %>

<%= link_to 'Show', @mdl_course %> |
<%= link_to 'Back', mdl_courses_path %>

app/views/mdl_courses/index.html.erb
  <link rel="stylesheet" href="style.css">
  <title>Ingreso</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <div id="panelLogin" class="container-fluid">

    <div id="panelLoginInterior" class="panel panel-default">

    <div class="panel-body">


      <div class="col-lg-12">
        <h1>Buscar cursos</h1>
        <h1></h1>
        <h2>Ingresa el nombre del curso </h2>
        <h1></h1>
        <input type="text" class="form-control" id="terminoABucar" name="terminoABuscar" <%= @terminoABuscar%>>
        <h1></h1>
      <input id = "botonDecurso" type="submit" class="btn btn-primary btn-block" value="Buscar">
      <h1></h1>

      </div>

    </div>
    </div>
  </div>


<p id="notice"><%= notice %></p>

<h1>Mdl Courses</h1>

<table>
  <thead>
    <tr>

      <th>email</th>

    </tr>
  </thead>

  <tbody>
    <% @mdl_users.each do |mdl_users| %>
      <tr>
        <td><%= email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mdl Course', new_mdl_course_path %>

</html>

app/views/mdl_courses/new.html.erb
<h1>New Mdl Course</h1>

<%= render 'form', mdl_course: @mdl_course %>

<%= link_to 'Back', mdl_courses_path %>

app/views/mdl_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @mdl_course.category %>
</p>

<p>
  <strong>Sortorder:</strong>
  <%= @mdl_course.sortorder %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @mdl_course.fullname %>
</p>

<p>
  <strong>Shortname:</strong>
  <%= @mdl_course.shortname %>
</p>

<p>
  <strong>Idnumber:</strong>
  <%= @mdl_course.idnumber %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @mdl_course.summary %>
</p>

<p>
  <strong>Summaryformat:</strong>
  <%= @mdl_course.summaryformat %>
</p>

<p>
  <strong>Format:</strong>
  <%= @mdl_course.format %>
</p>

<p>
  <strong>Showgrades:</strong>
  <%= @mdl_course.showgrades %>
</p>

<p>
  <strong>Newsitems:</strong>
  <%= @mdl_course.newsitems %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @mdl_course.startdate %>
</p>

<p>
  <strong>Marker:</strong>
  <%= @mdl_course.marker %>
</p>

<p>
  <strong>Maxbytes:</strong>
  <%= @mdl_course.maxbytes %>
</p>

<p>
  <strong>Legacyfiles:</strong>
  <%= @mdl_course.legacyfiles %>
</p>

<p>
  <strong>Showreports:</strong>
  <%= @mdl_course.showreports %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @mdl_course.visible %>
</p>

<p>
  <strong>Visibleold:</strong>
  <%= @mdl_course.visibleold %>
</p>

<p>
  <strong>Groupmode:</strong>
  <%= @mdl_course.groupmode %>
</p>

<p>
  <strong>Groupmodeforce:</strong>
  <%= @mdl_course.groupmodeforce %>
</p>

<p>
  <strong>Defaultgroupingid:</strong>
  <%= @mdl_course.defaultgroupingid %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @mdl_course.lang %>
</p>

<p>
  <strong>Calendartype:</strong>
  <%= @mdl_course.calendartype %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @mdl_course.theme %>
</p>

<p>
  <strong>Timecreated:</strong>
  <%= @mdl_course.timecreated %>
</p>

<p>
  <strong>Timemodified:</strong>
  <%= @mdl_course.timemodified %>
</p>

<p>
  <strong>Requested:</strong>
  <%= @mdl_course.requested %>
</p>

<p>
  <strong>Enablecompletion:</strong>
  <%= @mdl_course.enablecompletion %>
</p>

<p>
  <strong>Completionnotify:</strong>
  <%= @mdl_course.completionnotify %>
</p>

<p>
  <strong>Cacherev:</strong>
  <%= @mdl_course.cacherev %>
</p>

<%= link_to 'Edit', edit_mdl_course_path(@mdl_course) %> |
<%= link_to 'Back', mdl_courses_path %>