config/routes.rb
Rails.application.routes.draw do

  resources :mdl_resources
  resources :mdl_contexts
  resources :mdl_role_assignments
  root 'welcome#index'

  resources :mdl_events
  resources :mdl_forum_posts
  resources :mdl_forum_discussions
  resources :mdl_forums
  resources :mdl_courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mdl_users

 get 'mdl_events/eventosPorCurso/:courseid', to: 'mdl_events#eventosPorCurso'
get 'mdl_users/', to: 'mdl_users#index'
  get 'mdl_forums/forosPorCurso/:course', to: 'mdl_forums#forosPorCurso'
  get 'mdl_forum_discussions/discusionesPorForo/:forum', to: 'mdl_forum_discussions#discusionesPorForo'
  get 'mdl_forums_posts/postPorDiscusionPrincipal/:discussion', to: 'mdl_forum_posts#postPorDiscusionPrincipal'
  get 'mdl_forums_posts/postRespuestas/:discussion/', to: 'mdl_forum_posts#postRespuestas'
  get 'mdl_resources/obtenerRecursosPorCurso/:course', to: 'mdl_resources#obtenerRecursosPorCurso'
  post 'mdl_contexts/misCursos/', to: 'mdl_contexts#misCursos'
  post 'mdl_users/verifEmail', to: 'mdl_users#verifEmail'
  get 'mdl_users/emailErroneo', to: 'mdl_users#emailErroneo'
  get 'mdl_users/vcontrasena/:contrasena', to: 'mdl_users#vcontrasena'
  get 'mdl_contexts/course/:id', to: 'mdl_contexts#course'
  get 'mdl_context/buscar', to: 'mdl_context#buscar'
  get 'mdl_resources/sinRecursos/:course', to: 'mdl_resources#sinRecursos'
  get 'mdl_events/sinEventos/:courseid', to: 'mdl_events#sinEventos'
  get 'mdl_forums/sinForos', to: 'mdl_forums#sinForos'
  get 'mdl_forum_discussions/sinDiscusiones', to: 'mdl_forum_discussions#sinDiscusiones'
  get 'mdl_forum_posts/sinPosts',to: 'mdl_forum_posts#sinPosts'
end

app/models/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: 'from@example.com'
  layout 'mailer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mdl_context.rb
class MdlContext < ApplicationRecord
    self.table_name = "mdl_context"
     has_many :mdl_role_assignments
     has_many :mdl_courses 
end

app/models/mdl_course.rb
class MdlCourse < ApplicationRecord

    self.table_name = "mdl_course"
    belongs_to :mdl_context
end

app/models/mdl_event.rb
class MdlEvent < ApplicationRecord

self.table_name = "mdl_event"

end

app/models/mdl_forum.rb
class MdlForum < ApplicationRecord

self.table_name = "mdl_forum"
self.inheritance_column = :_type_disabled
end

app/models/mdl_forum_discussion.rb
class MdlForumDiscussion < ApplicationRecord

  self.table_name = "mdl_forum_discussions"

end

app/models/mdl_forum_post.rb
class MdlForumPost < ApplicationRecord

  self.table_name = "mdl_forum_posts"

end

app/models/mdl_resource.rb
class MdlResource < ApplicationRecord

    self.table_name = "mdl_resource"


end

app/models/mdl_role_assignment.rb
class MdlRoleAssignment < ApplicationRecord

   belongs_to :mdl_context
   


end

app/models/mdl_user.rb
class MdlUser< ApplicationRecord

  has_secure_password

  self.table_name = "mdl_user"


end

app/controllers/mdl_resources_controller.rb
class MdlResourcesController < ApplicationController
  before_action :set_mdl_resource, only: [:show, :edit, :update, :destroy]

  # GET /mdl_resources
  # GET /mdl_resources.json
  def index
    @mdl_resources = MdlResource.all
  end

  # GET /mdl_resources/1
  # GET /mdl_resources/1.json
  def show
  end

  # GET /mdl_resources/new
  def new
    @mdl_resource = MdlResource.new
  end

  def sinRecursos



  end

  def descarga

    render :action => "descarga"

  end



  def obtenerRecursosPorCurso

    @mdl_resources = MdlResource.select(:name,:course).where("course = ?", params[:course])

    if @mdl_resources.nil? == true || @mdl_resources.blank? == true

         redirect_to :action =>"sinRecursos", :course => params[:course]

    else

    return @mdl_resources

    end
  end



  # GET /mdl_resources/1/edit
  def edit
  end

  # POST /mdl_resources
  # POST /mdl_resources.json
  def create
    @mdl_resource = MdlResource.new(mdl_resource_params)

    respond_to do |format|
      if @mdl_resource.save
        format.html { redirect_to @mdl_resource, notice: 'Mdl resource was successfully created.' }
        format.json { render :show, status: :created, location: @mdl_resource }
      else
        format.html { render :new }
        format.json { render json: @mdl_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mdl_resources/1
  # PATCH/PUT /mdl_resources/1.json
  def update
    respond_to do |format|
      if @mdl_resource.update(mdl_resource_params)
        format.html { redirect_to @mdl_resource, notice: 'Mdl resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @mdl_resource }
      else
        format.html { render :edit }
        format.json { render json: @mdl_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mdl_resources/1
  # DELETE /mdl_resources/1.json
  def destroy
    @mdl_resource.destroy
    respond_to do |format|
      format.html { redirect_to mdl_resources_url, notice: 'Mdl resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mdl_resource
      @mdl_resource = MdlResource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mdl_resource_params
      params.require(:mdl_resource).permit(:course, :name, :intro, :introformat, :tobemigrated, :legacyfiles, :legacyfileslast, :display, :displayoptions, :filterfiles, :revision, :timemodified)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mdl_contexts_helper.rb
module MdlContextsHelper
end

app/helpers/mdl_courses_helper.rb
module MdlCoursesHelper
end

app/helpers/mdl_events_helper.rb
module MdlEventsHelper
end

app/helpers/mdl_forum_posts_helper.rb
module MdlForumPostsHelper
end

app/helpers/mdl_forums_helper.rb
module MdlForumsHelper
end

app/helpers/mdl_resources_helper.rb
module MdlResourcesHelper
end

app/helpers/mdl_users_helper.rb
module MdlUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mdl_resources/_form.html.erb
<%= form_for(mdl_resource) do |f| %>
  <% if mdl_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mdl_resource.errors.count, "error") %> prohibited this mdl_resource from being saved:</h2>

      <ul>
      <% mdl_resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course %>
    <%= f.text_field :course %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :intro %>
    <%= f.text_area :intro %>
  </div>

  <div class="field">
    <%= f.label :introformat %>
    <%= f.number_field :introformat %>
  </div>

  <div class="field">
    <%= f.label :tobemigrated %>
    <%= f.number_field :tobemigrated %>
  </div>

  <div class="field">
    <%= f.label :legacyfiles %>
    <%= f.number_field :legacyfiles %>
  </div>

  <div class="field">
    <%= f.label :legacyfileslast %>
    <%= f.text_field :legacyfileslast %>
  </div>

  <div class="field">
    <%= f.label :display %>
    <%= f.number_field :display %>
  </div>

  <div class="field">
    <%= f.label :displayoptions %>
    <%= f.text_area :displayoptions %>
  </div>

  <div class="field">
    <%= f.label :filterfiles %>
    <%= f.number_field :filterfiles %>
  </div>

  <div class="field">
    <%= f.label :revision %>
    <%= f.text_field :revision %>
  </div>

  <div class="field">
    <%= f.label :timemodified %>
    <%= f.text_field :timemodified %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mdl_resources/descarga.html.erb
<%= form_tag(controller: "mdl_resources", action: "descarga", method: "get") do |f| %>

<title>Ingreso</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrapo/3.3.7/js/bootstrap.min.js"></script>

<div id="panelLogin" class="container-fluid">

  <div id="panelLoginInterior" class="panel panel-default">

    <div class="panel-body">


               <div class="col-lg-12"><h1>Se esta dedscargando el material que solicitaste </h1></div>



    </div>
  </div>
</div>
<% end %>

app/views/mdl_resources/edit.html.erb
<h1>Editing Mdl Resource</h1>

<%= render 'form', mdl_resource: @mdl_resource %>

<%= link_to 'Show', @mdl_resource %> |
<%= link_to 'Back', mdl_resources_path %>

app/views/mdl_resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mdl Resources</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Name</th>
      <th>Intro</th>
      <th>Introformat</th>
      <th>Tobemigrated</th>
      <th>Legacyfiles</th>
      <th>Legacyfileslast</th>
      <th>Display</th>
      <th>Displayoptions</th>
      <th>Filterfiles</th>
      <th>Revision</th>
      <th>Timemodified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mdl_resources.each do |mdl_resource| %>
      <tr>
        <td><%= mdl_resource.course %></td>
        <td><%= mdl_resource.name %></td>
        <td><%= mdl_resource.intro %></td>
        <td><%= mdl_resource.introformat %></td>
        <td><%= mdl_resource.tobemigrated %></td>
        <td><%= mdl_resource.legacyfiles %></td>
        <td><%= mdl_resource.legacyfileslast %></td>
        <td><%= mdl_resource.display %></td>
        <td><%= mdl_resource.displayoptions %></td>
        <td><%= mdl_resource.filterfiles %></td>
        <td><%= mdl_resource.revision %></td>
        <td><%= mdl_resource.timemodified %></td>
        <td><%= link_to 'Show', mdl_resource %></td>
        <td><%= link_to 'Edit', edit_mdl_resource_path(mdl_resource) %></td>
        <td><%= link_to 'Destroy', mdl_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mdl Resource', new_mdl_resource_path %>

app/views/mdl_resources/new.html.erb
<h1>New Mdl Resource</h1>

<%= render 'form', mdl_resource: @mdl_resource %>

<%= link_to 'Back', mdl_resources_path %>

app/views/mdl_resources/obtenerRecursosPorCurso.html.erb
<%= form_for :mdl_resources, :url => { :action => :obtenerRecursosPorCurso } do |f| %>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<nav class="navbar navbar-inverse navbar-fixed-top">
 <div class="container-fluid">
   <ul class="nav navbar-nav">
     <li><%=link_to("Mis cursos", :back)%></li>
     <li><%= link_to "Ir a eventos", controller: "mdl_events", action: "eventosPorCurso", courseid:  @mdl_resources.pluck(:course)%></li>
   </ul>
 </div>
</nav>



<div class="row">
  <div class="col-md-12 "><h2>Material</h2></div>
</div>

<% @mdl_resources.each do |mdl_resources| %>

<div class="row">
<div class="col-md-12 courseButton"><%=  mdl_resources.name %></div>
</div>
<% end %>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="#"></a>
   </div>
   <ul class="nav navbar-nav">
     <li class="active"><a href="#">Mis Cursos</a></li>
     <li><a href="#">Buscar Cursos</a></li>
     <li><a href="#">Mi Usuario</a></li>
     <li><a href="#">Mis Mensajes</a></li>
   </ul>
 </div>
</nav>



<% end %>

app/views/mdl_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @mdl_resource.course %>
</p>

<p>
  <strong>Name:</strong>
  <%= @mdl_resource.name %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @mdl_resource.intro %>
</p>

<p>
  <strong>Introformat:</strong>
  <%= @mdl_resource.introformat %>
</p>

<p>
  <strong>Tobemigrated:</strong>
  <%= @mdl_resource.tobemigrated %>
</p>

<p>
  <strong>Legacyfiles:</strong>
  <%= @mdl_resource.legacyfiles %>
</p>

<p>
  <strong>Legacyfileslast:</strong>
  <%= @mdl_resource.legacyfileslast %>
</p>

<p>
  <strong>Display:</strong>
  <%= @mdl_resource.display %>
</p>

<p>
  <strong>Displayoptions:</strong>
  <%= @mdl_resource.displayoptions %>
</p>

<p>
  <strong>Filterfiles:</strong>
  <%= @mdl_resource.filterfiles %>
</p>

<p>
  <strong>Revision:</strong>
  <%= @mdl_resource.revision %>
</p>

<p>
  <strong>Timemodified:</strong>
  <%= @mdl_resource.timemodified %>
</p>

<%= link_to 'Edit', edit_mdl_resource_path(@mdl_resource) %> |
<%= link_to 'Back', mdl_resources_path %>

app/views/mdl_resources/sinRecursos.html.erb
<%= form_tag(controller: "mdl_resources", action: "sinRecursos", method: "get") do |f| %>

<title>Ingreso</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrapo/3.3.7/js/bootstrap.min.js"></script>

<div id="panelLogin" class="container-fluid">

  <div id="panelLoginInterior" class="panel panel-default">

    <div class="panel-body">


               <div class="col-lg-12"><h1>Lo sentimos, en este curso aun no hay material </h1></div>
               <div class="btn btn-default"><%= link_to "Ir a eventos", controller: "mdl_events", action: "eventosPorCurso", courseid: params[:course]%></div>



    </div>
  </div>
</div>
<% end %>