config/routes.rb
Rails.application.routes.draw do

  resources :mdl_resources
  resources :mdl_contexts
  resources :mdl_role_assignments
  root 'welcome#index'

  resources :mdl_events
  resources :mdl_forum_posts
  resources :mdl_forum_discussions
  resources :mdl_forums
  resources :mdl_courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mdl_users

 get 'mdl_events/eventosPorCurso/:courseid', to: 'mdl_events#eventosPorCurso'
get 'mdl_users/', to: 'mdl_users#index'
  get 'mdl_forums/forosPorCurso/:course', to: 'mdl_forums#forosPorCurso'
  get 'mdl_forum_discussions/discusionesPorForo/:forum', to: 'mdl_forum_discussions#discusionesPorForo'
  get 'mdl_forums_posts/postPorDiscusionPrincipal/:discussion', to: 'mdl_forum_posts#postPorDiscusionPrincipal'
  get 'mdl_forums_posts/postRespuestas/:discussion/', to: 'mdl_forum_posts#postRespuestas'
  get 'mdl_resources/obtenerRecursosPorCurso/:course', to: 'mdl_resources#obtenerRecursosPorCurso'
  post 'mdl_contexts/misCursos/', to: 'mdl_contexts#misCursos'
  post 'mdl_users/verifEmail', to: 'mdl_users#verifEmail'
  get 'mdl_users/emailErroneo', to: 'mdl_users#emailErroneo'
  get 'mdl_users/vcontrasena/:contrasena', to: 'mdl_users#vcontrasena'
  get 'mdl_contexts/course/:id', to: 'mdl_contexts#course'
  get 'mdl_context/buscar', to: 'mdl_context#buscar'
  get 'mdl_resources/sinRecursos/:course', to: 'mdl_resources#sinRecursos'
  get 'mdl_events/sinEventos/:courseid', to: 'mdl_events#sinEventos'
  get 'mdl_forums/sinForos', to: 'mdl_forums#sinForos'
  get 'mdl_forum_discussions/sinDiscusiones', to: 'mdl_forum_discussions#sinDiscusiones'
  get 'mdl_forum_posts/sinPosts',to: 'mdl_forum_posts#sinPosts'
end

app/models/application_mailer.rb
class ApplicationMailer < ActionMailer::Base
  default from: 'from@example.com'
  layout 'mailer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/mdl_context.rb
class MdlContext < ApplicationRecord
    self.table_name = "mdl_context"
     has_many :mdl_role_assignments
     has_many :mdl_courses 
end

app/models/mdl_course.rb
class MdlCourse < ApplicationRecord

    self.table_name = "mdl_course"
    belongs_to :mdl_context
end

app/models/mdl_event.rb
class MdlEvent < ApplicationRecord

self.table_name = "mdl_event"

end

app/models/mdl_forum.rb
class MdlForum < ApplicationRecord

self.table_name = "mdl_forum"
self.inheritance_column = :_type_disabled
end

app/models/mdl_forum_discussion.rb
class MdlForumDiscussion < ApplicationRecord

  self.table_name = "mdl_forum_discussions"

end

app/models/mdl_forum_post.rb
class MdlForumPost < ApplicationRecord

  self.table_name = "mdl_forum_posts"

end

app/models/mdl_resource.rb
class MdlResource < ApplicationRecord

    self.table_name = "mdl_resource"


end

app/models/mdl_role_assignment.rb
class MdlRoleAssignment < ApplicationRecord

   belongs_to :mdl_context
   


end

app/models/mdl_user.rb
class MdlUser< ApplicationRecord

  has_secure_password

  self.table_name = "mdl_user"


end

app/controllers/mdl_events_controller.rb
class MdlEventsController < ApplicationController
  before_action :set_mdl_event, only: [:show, :edit, :update, :destroy]

  # GET /mdl_events
  # GET /mdl_events.json
  def index
    @mdl_events = MdlEvent.all
  end

  # GET /mdl_events/1
  # GET /mdl_events/1.json
  def show
  end



  def sinEventos

  end



  def eventosPorCurso

    @mdl_events = MdlEvent.select(:id, :name, :courseid).where("courseid = ?", params[:courseid])

    if @mdl_events.nil? == true || @mdl_events.blank? == true

         render :action =>"sinEventos"

    else

    return @mdl_events

    end
  end

  # GET /mdl_events/new
  # GET /mdl_events/new
  def new
    @mdl_event = MdlEvent.new
  end

  # GET /mdl_events/1/edit
  def edit
  end

  # POST /mdl_events
  # POST /mdl_events.json
  def create
    @mdl_event = MdlEvent.new(mdl_event_params)

    respond_to do |format|
      if @mdl_event.save
        format.html { redirect_to @mdl_event, notice: 'Mdl event was successfully created.' }
        format.json { render :show, status: :created, location: @mdl_event }
      else
        format.html { render :new }
        format.json { render json: @mdl_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mdl_events/1
  # PATCH/PUT /mdl_events/1.json
  def update
    respond_to do |format|
      if @mdl_event.update(mdl_event_params)
        format.html { redirect_to @mdl_event, notice: 'Mdl event was successfully updated.' }
        format.json { render :show, status: :ok, location: @mdl_event }
      else
        format.html { render :edit }
        format.json { render json: @mdl_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mdl_events/1
  # DELETE /mdl_events/1.json
  def destroy
    @mdl_event.destroy
    respond_to do |format|
      format.html { redirect_to mdl_events_url, notice: 'Mdl event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mdl_event
      @mdl_event = MdlEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mdl_event_params
      params.require(:mdl_event).permit(:name, :description, :format, :courseid, :groupid, :userid, :repeatid, :modulename, :instance, :eventtype, :timestart, :timeduration, :visible, :uuid, :sequence, :timemodified, :subscriptionid)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mdl_contexts_helper.rb
module MdlContextsHelper
end

app/helpers/mdl_courses_helper.rb
module MdlCoursesHelper
end

app/helpers/mdl_events_helper.rb
module MdlEventsHelper
end

app/helpers/mdl_forum_posts_helper.rb
module MdlForumPostsHelper
end

app/helpers/mdl_forums_helper.rb
module MdlForumsHelper
end

app/helpers/mdl_resources_helper.rb
module MdlResourcesHelper
end

app/helpers/mdl_users_helper.rb
module MdlUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mdl_events/_form.html.erb
<%= form_for(mdl_event) do |f| %>
  <% if mdl_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mdl_event.errors.count, "error") %> prohibited this mdl_event from being saved:</h2>

      <ul>
      <% mdl_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :format %>
    <%= f.number_field :format %>
  </div>

  <div class="field">
    <%= f.label :courseid %>
    <%= f.text_field :courseid %>
  </div>

  <div class="field">
    <%= f.label :groupid %>
    <%= f.text_field :groupid %>
  </div>

  <div class="field">
    <%= f.label :userid %>
    <%= f.text_field :userid %>
  </div>

  <div class="field">
    <%= f.label :repeatid %>
    <%= f.text_field :repeatid %>
  </div>

  <div class="field">
    <%= f.label :modulename %>
    <%= f.text_field :modulename %>
  </div>

  <div class="field">
    <%= f.label :instance %>
    <%= f.text_field :instance %>
  </div>

  <div class="field">
    <%= f.label :eventtype %>
    <%= f.text_field :eventtype %>
  </div>

  <div class="field">
    <%= f.label :timestart %>
    <%= f.text_field :timestart %>
  </div>

  <div class="field">
    <%= f.label :timeduration %>
    <%= f.text_field :timeduration %>
  </div>

  <div class="field">
    <%= f.label :visible %>
    <%= f.number_field :visible %>
  </div>

  <div class="field">
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
  </div>

  <div class="field">
    <%= f.label :sequence %>
    <%= f.text_field :sequence %>
  </div>

  <div class="field">
    <%= f.label :timemodified %>
    <%= f.text_field :timemodified %>
  </div>

  <div class="field">
    <%= f.label :subscriptionid %>
    <%= f.text_field :subscriptionid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mdl_events/edit.html.erb
<h1>Editing Mdl Event</h1>

<%= render 'form', mdl_event: @mdl_event %>

<%= link_to 'Show', @mdl_event %> |
<%= link_to 'Back', mdl_events_path %>

app/views/mdl_events/eventosPorCurso.html.erb
<%= form_for :mdl_events, :url => { :action => :eventosPorCurso } do |f| %>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse navbar-fixed-top">
 <div class="container-fluid">
   <ul class="nav navbar-nav">
  <li><%= link_to "Ir a material", controller: "mdl_resources", action: "obtenerRecursosPorCurso", course: @mdl_events.pluck(:courseid)%></li>
  <li><%= link_to "Ir a foros", controller: "mdl_forums", action: "forosPorCurso", course: @mdl_events.pluck(:courseid)%></li>
</ul>
</div>
</nav>




<div class="row">
  <div class="col-md-12 "><h2>Eventos</h2></div>
</div>

<% @mdl_events.each do |mdl_events| %>

<div class="row">
<div class="col-md-12 courseButton"><%=  mdl_events.name %></div>
</div>
<% end %>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="#"></a>
   </div>
   <ul class="nav navbar-nav">
     <li class="active"><a href="#">Mis Cursos</a></li>
     <li><a href="#">Buscar Cursos</a></li>
     <li><a href="#">Mi Usuario</a></li>
     <li><a href="#">Mis Mensajes</a></li>
   </ul>
 </div>
</nav>



<% end %>

app/views/mdl_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mdl Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Format</th>
      <th>Courseid</th>
      <th>Groupid</th>
      <th>Userid</th>
      <th>Repeatid</th>
      <th>Modulename</th>
      <th>Instance</th>
      <th>Eventtype</th>
      <th>Timestart</th>
      <th>Timeduration</th>
      <th>Visible</th>
      <th>Uuid</th>
      <th>Sequence</th>
      <th>Timemodified</th>
      <th>Subscriptionid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mdl_events.each do |mdl_event| %>
      <tr>
        <td><%= mdl_event.name %></td>
        <td><%= mdl_event.description %></td>
        <td><%= mdl_event.format %></td>
        <td><%= mdl_event.courseid %></td>
        <td><%= mdl_event.groupid %></td>
        <td><%= mdl_event.userid %></td>
        <td><%= mdl_event.repeatid %></td>
        <td><%= mdl_event.modulename %></td>
        <td><%= mdl_event.instance %></td>
        <td><%= mdl_event.eventtype %></td>
        <td><%= mdl_event.timestart %></td>
        <td><%= mdl_event.timeduration %></td>
        <td><%= mdl_event.visible %></td>
        <td><%= mdl_event.uuid %></td>
        <td><%= mdl_event.sequence %></td>
        <td><%= mdl_event.timemodified %></td>
        <td><%= mdl_event.subscriptionid %></td>
        <td><%= link_to 'Show', mdl_event %></td>
        <td><%= link_to 'Edit', edit_mdl_event_path(mdl_event) %></td>
        <td><%= link_to 'Destroy', mdl_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mdl Event', new_mdl_event_path %>

app/views/mdl_events/new.html.erb
<h1>New Mdl Event</h1>

<%= render 'form', mdl_event: @mdl_event %>

<%= link_to 'Back', mdl_events_path %>

app/views/mdl_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mdl_event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mdl_event.description %>
</p>

<p>
  <strong>Format:</strong>
  <%= @mdl_event.format %>
</p>

<p>
  <strong>Courseid:</strong>
  <%= @mdl_event.courseid %>
</p>

<p>
  <strong>Groupid:</strong>
  <%= @mdl_event.groupid %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @mdl_event.userid %>
</p>

<p>
  <strong>Repeatid:</strong>
  <%= @mdl_event.repeatid %>
</p>

<p>
  <strong>Modulename:</strong>
  <%= @mdl_event.modulename %>
</p>

<p>
  <strong>Instance:</strong>
  <%= @mdl_event.instance %>
</p>

<p>
  <strong>Eventtype:</strong>
  <%= @mdl_event.eventtype %>
</p>

<p>
  <strong>Timestart:</strong>
  <%= @mdl_event.timestart %>
</p>

<p>
  <strong>Timeduration:</strong>
  <%= @mdl_event.timeduration %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @mdl_event.visible %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @mdl_event.uuid %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @mdl_event.sequence %>
</p>

<p>
  <strong>Timemodified:</strong>
  <%= @mdl_event.timemodified %>
</p>

<p>
  <strong>Subscriptionid:</strong>
  <%= @mdl_event.subscriptionid %>
</p>

<%= link_to 'Edit', edit_mdl_event_path(@mdl_event) %> |
<%= link_to 'Back', mdl_events_path %>

app/views/mdl_events/sinEventos.html.erb
<%= form_tag(controller: "mdl_events", action: "sinEventos", method: "get") do |f| %>

<title>Ingreso</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrapo/3.3.7/js/bootstrap.min.js"></script>

<div id="panelLogin" class="container-fluid">

  <div id="panelLoginInterior" class="panel panel-default">

    <div class="panel-body">


               <div class="col-lg-12"><h1>Lo sentimos, en este curso aun no hay eventos </h1></div>
              <div class="btn btn-default"><%= link_to "Volver al material", :back %></div>
                <div class="btn btn-default"><%= link_to "Ir a foros", :back %></div>



    </div>
  </div>
</div>
<% end %>